---
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
- pattern: org.apache.cassandra.metrics<type=(Connection|Streaming), scope=(\S*), name=(\S*)><>(Count|Value)
  name: cassandra_$1_$3
  labels:
    address: "$2"
- pattern: org.apache.cassandra.metrics<type=HintedHandOffManager, name=(Hints_created|Hints_not_stored)-(\S*)><>(Count|Value)
  name: cassandra_hintedhandoffmanager_$1
  labels:
    address: "$2"
- pattern: org.apache.cassandra.metrics<type=(\S*)(?:, ((?!scope)\S*)=(\S*))?(?:, scope=(\S*))?,
    name=(\S*)><>(Count|Value)
  name: cassandra_$1_$5
  labels:
    "$1": "$4"
    "$2": "$3"
